node {
  name: "Const"
  op: "Const"
  attr {
    key: "_output_shapes"
    value {
      list {
        shape {
        }
      }
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_BFLOAT16
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BFLOAT16
        tensor_shape {
        }
        tensor_content: "\000@"
      }
    }
  }
}
versions {
  producer: 716
}
